services:
   
    postgres_db:
        image: postgres:14
        container_name: postgres_db
        environment:
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            POSTGRES_DB: ${DATABASE_NAME}
        volumes:
            - ./scripts/pg_init.sql:/docker-entrypoint-initdb.d/pg_init.sql
        ports:
            - "5434:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s

    etl_app:
        build: .
        container_name: etl_app
        depends_on:
            postgres_db:
                condition: service_healthy
        environment:
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: postgres_db
            PORT: 5432
    
    dbt:
        image: ghcr.io/dbt-labs/dbt-postgres:1.9.latest
        container_name: dbt
        volumes:
            - ./dbt/:/src/dbt
            - ./profiles.yml:/root/.dbt/profiles.yml
        working_dir: /src/dbt
        depends_on:
           postgres_db:
               condition: service_healthy
        environment:
            DBT_PROFILES_DIR: "/root/.dbt"
            DATABASE_NAME: ${DATABASE_NAME}
            DATABASE_USER: ${DATABASE_USER}
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
            DATABASE_HOST: postgres_db
            DATABASE_PORT: 5432
        entrypoint: ["/bin/bash", "-c"]
        command: 
            - |  
                echo '🚀 Running dbt build...';
                dbt deps --profiles-dir /root/.dbt;
                dbt build --profiles-dir /root/.dbt;
                echo '✅ dbt build complete.';
                tail -f /dev/null

    

volumes:
  postgres_data: