dbt_store:
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DATABASE_HOST') }}"
      port: "{{ env_var('DATABASE_PORT') | int }}"
      user: "{{ env_var('DATABASE_USER') }}"
      password: "{{ env_var('DATABASE_PASSWORD') }}"
      dbname: "{{ env_var('DATABASE_NAME') }}"
      schema: bronze
      threads: 1
  target: dev